Allow for no filter segment to getRunningConfig.
Juniper/netconf-java pull request #42
Opened 2020-11-24 20:22 UTC by esend7881

- I found this needed in my set up. For some reason, when I left confgtree blank, the default `EMPTY_CONFIGURATION_TAG` (which is `<configuration></configuration>`) did not return anything
- However, when I fully ensured the `<filter ... >` section is removed, I got the data I was seeking.
- I'm not sure if this is some nuance with my netopeer2 set up, but until I removed that filter section, I got not data back.

Now, I don't think this code is in a final state! I see it as the start of a converstaion. I'm not sure how you'd want to implement this, perhaps there should be a pure `getRunningConfigNoFilter` function that will take on this feature more clearly than sending in a `null` value manually.

2020-12-08 11:13 UTC, ydnath commented
@peterjhill Please review

2020-12-08 15:32 UTC, peterjhill requested changes
Please check my PR comment. It looks like the change you made could also be made in another method in the same class.

Let me know if you disagree.
Thanks,
Peter

2020-12-14 22:38 UTC, peterjhill commented
@ydnath - I think this is fine to merge. There is another method we might want in the future to update with same support, but as this is the first request for this change, it is probably not bothering anyone. I can see how it would be good for @esend7881  to use mainline version of this instead of an in-house build that has the fix he needs..

YMMV

2020-12-14 22:39 UTC, peterjhill approved these changes
okay to merge

2020-12-15 04:17 UTC, merged